version: '3.8'

services:
  alidiff:
    build: .
    volumes:
      - .:/workspace
      - /media/data:/media/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 